name: Run Python Script Every 1 Minute

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install pandas

    - name: Run Python script
      run: python dumpcsv.py
        git config --global user.email "alireza.naziri@gmail.com"
        git config --global user.name "alirezax2"
        git add tiprank/random_data.csv
        git commit -m "Add random_data.csv via GitHub Action"
        git push
    # - name: Commit and Push Changes
    #   uses: stefanzweifel/git-auto-commit-action@v4
    #   with:
    #     commit_message: "Generate CSV file"
    #     branch: ${{ github.ref }}
    #     commit_user_name: GitHub Actions
    #     commit_user_email: actions@users.noreply.github.com
