name: Generate and Commit CSV

on:
  schedule:
    # Runs at every minute
    - cron: '*/1 * * * *'

jobs:
  generate-and-commit-csv:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Setup Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Install the Python version needed

      # Step 3: Install dependencies
      - name: Install pandas
        run: pip install pandas

      # Step 4: Execute the Python script to create a CSV
      - name: Generate CSV
        run: python dumpcsv.py

      # Step 5: Commit and push the generated CSV file if there are changes
      - name: Commit and push changes
        run:          git config --global user.name 'alirezax2'
          git config --global user.email 'alireza.naziri@gmail.com'
          git add -A
          git commit -m "Automated CSV update" -a echo "No changes to commit"
          git push
